version : ‘3.9’
 
services:
    postgresql_database:
      image: postgres
      ports:
           - 5432:5432
     
      volumes:
         - ./data/postgresql_database:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: postgres_db_cont
    
    
       
      
      

      #  networks:
      #    app_net:
      #     ipv4_address: 192.168.0.3  
 
    
    

    pgadmin:
        image: dpage/pgadmin4
        environment:
           - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
           - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
          - "5050:80"  
        restart: always
        volumes:
           - ./data/pgadmin-data:/var/lib/pgadmin
    
    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      ports:
          - 8000:8000
      image: app:django
      container_name : blogpost_container

      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      depends_on:
        - postgresql_database


# volumes:
#  postgresql_database-data:
#   pgadmin-data:
# command: ["./wait-for-it.sh", "db:5432", "--", "python", "app.py"]